var json_UGRRMappingProjectDataSetNov42024_5 = {
    "type": "FeatureCollection",
    "name": "UGRRMappingProjectDataSetNov42024_5",
    "crs": {"type": "name", "properties": {"name": "urn:ogc:def:crs:OGC:1.3:CRS84"}},
    "features": [{
        "type": "Feature",
        "properties": {
            "Title": "Stewart House Hotel",
            "Name(s) related to site": "Stewart",
            "freedom seeker name related to site": null,
            "short description": "Peter Stewart built the Stewart House hotel in the middle of Wilmington with its back on the Riverside",
            "More information": null,
            "type (stationary)": "safe house",
            "Routes": null,
            "Town/ City": "Wilmington",
            "present day county": "Will",
            "state": "IL",
            "date of settlement in Illinois": null,
            "Time Active": "1846",
            "Date Range of Travel Through Illinois": null,
            "source type": "Secondary Source",
            "Reliability": "Verifiable",
            "lat": 41.30956,
            "lon": -88.14793,
            "geoAddress": null,
            "Nearest Current Address": null,
            "Access": "private",
            "StartYear": "1/1/1846",
            "EndYear": "12/31/1846",
            "Start Year": "1846-01-01",
            "End Year": "1846-12-31",
            "entered by": null,
            "entry date": null,
            "link to data entry template": null,
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\download (1).jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-88.147929, 41.30956]}
    }, {
        "type": "Feature",
        "properties": {
            "Title": "Jan and Aagje Ton Farm",
            "Name(s) related to site": null,
            "freedom seeker name related to site": null,
            "short description": "Farm that was a safe house",
            "More information": null,
            "type (stationary)": "safe house",
            "Routes": null,
            "Town/ City": "Chicago",
            "present day county": "Cook",
            "state": "IL",
            "date of settlement in Illinois": "1853",
            "Time Active": "1850S",
            "Date Range of Travel Through Illinois": null,
            "source type": "Secondary Source",
            "Reliability": "Verifiable",
            "lat": 41.65086,
            "lon": -87.60783,
            "geoAddress": null,
            "Nearest Current Address": "557 E 134th Pl, Chicago, IL 60827",
            "Access": "Public",
            "StartYear": "1/1/1853",
            "EndYear": "12/31/1859",
            "Start Year": "1853-01-01",
            "End Year": "1853-12-31",
            "entered by": "SC",
            "entry date": "9/13/2024",
            "link to data entry template": "Jan and Aagje Ton Farm.docx",
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\download (4).jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-87.60783169, 41.65086459]}
    }, {
        "type": "Feature",
        "properties": {
            "Title": "Samuel Cushing",
            "Name(s) related to site": "Elizabeth Cushing",
            "freedom seeker name related to site": null,
            "short description": "Assited freedom seekers, has a farm as well",
            "More information": null,
            "type (stationary)": "abolitionist/ safe house",
            "Routes": null,
            "Town/ City": "Crete",
            "present day county": "Will",
            "state": "IL",
            "date of settlement in Illinois": null,
            "Time Active": null,
            "Date Range of Travel Through Illinois": null,
            "source type": "Secondary Source",
            "Reliability": "Verifiable",
            "lat": 41.45796,
            "lon": -87.57399,
            "geoAddress": null,
            "Nearest Current Address": "841-905 E. Richton Road, Crete",
            "Access": "Private",
            "StartYear": "1/1/1846",
            "EndYear": "12/31/1846",
            "Start Year": "1846-01-01",
            "End Year": "1846-12-31",
            "entered by": "SC",
            "entry date": "9/23/2024",
            "link to data entry template": "Samuel Cushing.docx",
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\download (5).jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-87.57399095, 41.45795792]}
    }, {
        "type": "Feature",
        "properties": {
            "Title": "McCoy Farm",
            "Name(s) related to site": "John and Sabra McCoy",
            "freedom seeker name related to site": null,
            "short description": "Farm that was a safe house",
            "More information": null,
            "type (stationary)": "safe house",
            "Routes": null,
            "Town/ City": "Crete ",
            "present day county": "Will ",
            "state": "IL",
            "date of settlement in Illinois": null,
            "Time Active": null,
            "Date Range of Travel Through Illinois": null,
            "source type": "Secondary Source",
            "Reliability": "Verifiable",
            "lat": 41.47712,
            "lon": -87.66549,
            "geoAddress": null,
            "Nearest Current Address": null,
            "Access": "Public",
            "StartYear": "1/1/1836",
            "EndYear": "12/31/1836",
            "Start Year": "1836-01-01",
            "End Year": "1836-12-31",
            "entered by": "SC",
            "entry date": "9/23/2024",
            "link to data entry template": "McCoy Farm.docx",
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\download (6).jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-87.66548722, 41.47712246]}
    }, {
        "type": "Feature",
        "properties": {
            "Title": "Hannah and Moses Cook",
            "Name(s) related to site": "Victor Slain",
            "freedom seeker name related to site": null,
            "short description": "assisted freedom seekers; had a farm",
            "More information": null,
            "type (stationary)": "safehouse/ abolitionist",
            "Routes": null,
            "Town/ City": "Crete ",
            "present day county": "Will ",
            "state": "IL",
            "date of settlement in Illinois": "LATE 1838/ EARLY 1839",
            "Time Active": null,
            "Date Range of Travel Through Illinois": null,
            "source type": "Secondary Source",
            "Reliability": "Verifiable",
            "lat": 41.457,
            "lon": -87.58683,
            "geoAddress": null,
            "Nearest Current Address": null,
            "Access": "Private",
            "StartYear": "1/1/1838",
            "EndYear": "12/31/1839",
            "Start Year": "1838-01-01",
            "End Year": "1838-12-31",
            "entered by": "SC",
            "entry date": "9/23/2024",
            "link to data entry template": "Hannah and Moses Cook.docx",
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\download.jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-87.58682719, 41.45700274]}
    }, {
        "type": "Feature",
        "properties": {
            "Title": "Joseph and Dyantha Safford",
            "Name(s) related to site": "Mary Jane Safford",
            "freedom seeker name related to site": null,
            "short description": "assisted freedom seekers ",
            "More information": null,
            "type (stationary)": "safehouse/ abolitionist",
            "Routes": null,
            "Town/ City": "Crete",
            "present day county": "Will ",
            "state": "IL",
            "date of settlement in Illinois": null,
            "Time Active": null,
            "Date Range of Travel Through Illinois": null,
            "source type": "Secondary Source",
            "Reliability": "Verifiable",
            "lat": 41.44693,
            "lon": -87.60915,
            "geoAddress": null,
            "Nearest Current Address": null,
            "Access": "Public",
            "StartYear": "1/1/1838",
            "EndYear": "12/31/1839",
            "Start Year": "1838-01-01",
            "End Year": "1838-12-31",
            "entered by": "SC",
            "entry date": "9/23/2024",
            "link to data entry template": "Joseph and Dyantha Safford.docx",
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\underground-railroad-gettyimages-645161544.jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-87.60914626, 41.44693229]}
    }, {
        "type": "Feature",
        "properties": {
            "Title": "Beebe House",
            "Name(s) related to site": null,
            "freedom seeker name related to site": null,
            "short description": null,
            "More information": null,
            "type (stationary)": null,
            "Routes": null,
            "Town/ City": null,
            "present day county": null,
            "state": null,
            "date of settlement in Illinois": null,
            "Time Active": null,
            "Date Range of Travel Through Illinois": null,
            "source type": null,
            "Reliability": "Verifiable",
            "lat": 41.45732,
            "lon": -87.57396,
            "geoAddress": null,
            "Nearest Current Address": null,
            "Access": null,
            "StartYear": "1/1/1846",
            "EndYear": "12/31/1846",
            "Start Year": "1846-01-01",
            "End Year": "1846-12-31",
            "entered by": null,
            "entry date": null,
            "link to data entry template": null,
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\underground-railroad-routes-to-freedom.jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-87.5739606, 41.45732113]}
    }, {
        "type": "Feature",
        "properties": {
            "Title": "Batch Elder House",
            "Name(s) related to site": null,
            "freedom seeker name related to site": null,
            "short description": "Batch Elder was the postmaster in Crete and part of the network of safe houses",
            "More information": null,
            "type (stationary)": null,
            "Routes": null,
            "Town/ City": null,
            "present day county": null,
            "state": null,
            "date of settlement in Illinois": null,
            "Time Active": null,
            "Date Range of Travel Through Illinois": null,
            "source type": null,
            "Reliability": "Probable",
            "lat": 41.47506,
            "lon": -87.67492,
            "geoAddress": null,
            "Nearest Current Address": null,
            "Access": null,
            "StartYear": "1/1/1836",
            "EndYear": "12/31/1836",
            "Start Year": "1836-01-01",
            "End Year": "1836-12-31",
            "entered by": null,
            "entry date": null,
            "link to data entry template": null,
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\download (1).jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-87.6749151, 41.47505769]}
    }, {
        "type": "Feature",
        "properties": {
            "Title": "Browns",
            "Name(s) related to site": null,
            "freedom seeker name related to site": ",",
            "short description": "\"Brown'sCorner,\" there's a brown window in the Crete Congregational Church to honor this family",
            "More information": null,
            "type (stationary)": null,
            "Routes": null,
            "Town/ City": null,
            "present day county": null,
            "state": null,
            "date of settlement in Illinois": null,
            "Time Active": null,
            "Date Range of Travel Through Illinois": null,
            "source type": null,
            "Reliability": "Probable",
            "lat": 41.48125,
            "lon": -87.63828,
            "geoAddress": null,
            "Nearest Current Address": null,
            "Access": null,
            "StartYear": "1/1/1853",
            "EndYear": "12/31/1865",
            "Start Year": "1853-01-01",
            "End Year": "1853-12-31",
            "entered by": null,
            "entry date": null,
            "link to data entry template": null,
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\download (2).jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-87.63827691, 41.48125179]}
    }, {
        "type": "Feature",
        "properties": {
            "Title": "Lockport Congregational Church (Gladys Fox Museum)",
            "Name(s) related to site": null,
            "freedom seeker name related to site": null,
            "short description": null,
            "More information": null,
            "type (stationary)": null,
            "Routes": null,
            "Town/ City": "Lockport",
            "present day county": null,
            "state": null,
            "date of settlement in Illinois": null,
            "Time Active": null,
            "Date Range of Travel Through Illinois": null,
            "source type": null,
            "Reliability": "Verifiable",
            "lat": 41.58847,
            "lon": -88.05485,
            "geoAddress": null,
            "Nearest Current Address": null,
            "Access": null,
            "StartYear": "1/1/1853",
            "EndYear": "12/31/1859",
            "Start Year": "1853-01-01",
            "End Year": "1853-12-31",
            "entered by": "MV",
            "entry date": null,
            "link to data entry template": null,
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\download (3).jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-88.0548469, 41.5884713]}
    }, {
        "type": "Feature",
        "properties": {
            "Title": "Lockport Cemetery",
            "Name(s) related to site": "Masons, Coddings",
            "freedom seeker name related to site": null,
            "short description": null,
            "More information": null,
            "type (stationary)": null,
            "Routes": null,
            "Town/ City": null,
            "present day county": null,
            "state": null,
            "date of settlement in Illinois": null,
            "Time Active": null,
            "Date Range of Travel Through Illinois": null,
            "source type": null,
            "Reliability": "Probable",
            "lat": 41.5903,
            "lon": -88.0464,
            "geoAddress": null,
            "Nearest Current Address": null,
            "Access": null,
            "StartYear": "1/1/1846",
            "EndYear": "12/31/1846",
            "Start Year": "1846-01-01",
            "End Year": "1846-12-31",
            "entered by": null,
            "entry date": null,
            "link to data entry template": null,
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\download (4).jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-88.0464, 41.5903]}
    }, {
        "type": "Feature",
        "properties": {
            "Title": "I&M Canal at Lockport",
            "Name(s) related to site": null,
            "freedom seeker name related to site": null,
            "short description": null,
            "More information": null,
            "type (stationary)": null,
            "Routes": null,
            "Town/ City": "Lockport",
            "present day county": null,
            "state": null,
            "date of settlement in Illinois": null,
            "Time Active": null,
            "Date Range of Travel Through Illinois": null,
            "source type": null,
            "Reliability": "Probable",
            "lat": 41.59034,
            "lon": -88.05841,
            "geoAddress": null,
            "Nearest Current Address": null,
            "Access": null,
            "StartYear": "1/1/1836",
            "EndYear": "12/31/1836",
            "Start Year": "1836-01-01",
            "End Year": "1836-12-31",
            "entered by": null,
            "entry date": null,
            "link to data entry template": null,
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\download (5).jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-88.05840739, 41.59033536]}
    }, {
        "type": "Feature",
        "properties": {
            "Title": "I&M Canal at Wilmington",
            "Name(s) related to site": null,
            "freedom seeker name related to site": null,
            "short description": null,
            "More information": null,
            "type (stationary)": null,
            "Routes": null,
            "Town/ City": null,
            "present day county": null,
            "state": null,
            "date of settlement in Illinois": null,
            "Time Active": null,
            "Date Range of Travel Through Illinois": null,
            "source type": null,
            "Reliability": null,
            "lat": null,
            "lon": null,
            "geoAddress": null,
            "Nearest Current Address": null,
            "Access": null,
            "StartYear": "1/1/1838",
            "EndYear": "12/31/1839",
            "Start Year": "1838-01-01",
            "End Year": "1838-12-31",
            "entered by": null,
            "entry date": null,
            "link to data entry template": null,
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\download (6).jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": null
    }, {
        "type": "Feature",
        "properties": {
            "Title": "Lyonsville Cemetery",
            "Name(s) related to site": "Rufus Brown; George Vial",
            "freedom seeker name related to site": null,
            "short description": null,
            "More information": null,
            "type (stationary)": null,
            "Routes": null,
            "Town/ City": null,
            "present day county": null,
            "state": null,
            "date of settlement in Illinois": null,
            "Time Active": null,
            "Date Range of Travel Through Illinois": null,
            "source type": null,
            "Reliability": "Verifiable",
            "lat": 41.76558,
            "lon": -87.89641,
            "geoAddress": null,
            "Nearest Current Address": null,
            "Access": null,
            "StartYear": "1/1/1838",
            "EndYear": "12/31/1839",
            "Start Year": "1838-01-01",
            "End Year": "1838-12-31",
            "entered by": "MV",
            "entry date": null,
            "link to data entry template": null,
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\download.jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-87.89641105, 41.76558054]}
    }, {
        "type": "Feature",
        "properties": {
            "Title": "Denny Memorial",
            "Name(s) related to site": null,
            "freedom seeker name related to site": null,
            "short description": null,
            "More information": null,
            "type (stationary)": null,
            "Routes": null,
            "Town/ City": "Mokena",
            "present day county": null,
            "state": null,
            "date of settlement in Illinois": null,
            "Time Active": null,
            "Date Range of Travel Through Illinois": null,
            "source type": null,
            "Reliability": "Verifiable",
            "lat": 41.56373,
            "lon": -87.89027,
            "geoAddress": null,
            "Nearest Current Address": null,
            "Access": null,
            "StartYear": "1/1/1839",
            "EndYear": "12/31/1840",
            "Start Year": "1839-01-01",
            "End Year": "1839-12-31",
            "entered by": "MV",
            "entry date": null,
            "link to data entry template": null,
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\underground-railroad-gettyimages-645161544.jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-87.89026891, 41.56372737]}
    }, {
        "type": "Feature",
        "properties": {
            "Title": "Haven Tavern",
            "Name(s) related to site": "Abraham Lincoln? Havens",
            "freedom seeker name related to site": null,
            "short description": "south side of route 30, east of wolf road (south east corner), small brick monument (bricks from the tavern)",
            "More information": null,
            "type (stationary)": null,
            "Routes": null,
            "Town/ City": "New Lenox",
            "present day county": null,
            "state": null,
            "date of settlement in Illinois": null,
            "Time Active": null,
            "Date Range of Travel Through Illinois": null,
            "source type": null,
            "Reliability": "Verifiable",
            "lat": 41.50759,
            "lon": -87.91529,
            "geoAddress": null,
            "Nearest Current Address": null,
            "Access": null,
            "StartYear": "1/1/1840",
            "EndYear": "12/31/1841",
            "Start Year": "1840-01-01",
            "End Year": "1840-12-31",
            "entered by": "MV",
            "entry date": null,
            "link to data entry template": null,
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\underground-railroad-routes-to-freedom.jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-87.91528646, 41.50758681]}
    }, {
        "type": "Feature",
        "properties": {
            "Title": "Hadley Township",
            "Name(s) related to site": "Deacon Beach; Levi Savage",
            "freedom seeker name related to site": null,
            "short description": "No longer a township at all, had a Congregational Church",
            "More information": null,
            "type (stationary)": null,
            "Routes": null,
            "Town/ City": "Homer",
            "present day county": null,
            "state": null,
            "date of settlement in Illinois": null,
            "Time Active": null,
            "Date Range of Travel Through Illinois": null,
            "source type": null,
            "Reliability": "Verifiable",
            "lat": 41.56552,
            "lon": -87.95789,
            "geoAddress": null,
            "Nearest Current Address": null,
            "Access": null,
            "StartYear": "1/1/1841",
            "EndYear": "12/31/1842",
            "Start Year": "1841-01-01",
            "End Year": "1841-12-31",
            "entered by": "MV",
            "entry date": null,
            "link to data entry template": null,
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\download (1).jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-87.95788576, 41.56552207]}
    }, {
        "type": "Feature",
        "properties": {
            "Title": "German Farm",
            "Name(s) related to site": null,
            "freedom seeker name related to site": null,
            "short description": "Germans shared oral history of freedom seekers through Robbins to 1890s Black settlers",
            "More information": null,
            "type (stationary)": null,
            "Routes": null,
            "Town/ City": "Robbins",
            "present day county": "Cook",
            "state": "IL",
            "date of settlement in Illinois": null,
            "Time Active": null,
            "Date Range of Travel Through Illinois": null,
            "source type": null,
            "Reliability": "Probable",
            "lat": 41.64284,
            "lon": -87.70292,
            "geoAddress": null,
            "Nearest Current Address": null,
            "Access": null,
            "StartYear": "1/1/1842",
            "EndYear": "12/31/1843",
            "Start Year": "1842-01-01",
            "End Year": "1842-12-31",
            "entered by": null,
            "entry date": null,
            "link to data entry template": null,
            "Image Example": "C:\\Users\\MCornfield\\OneDrive - Breakthru Beverage Group\\Desktop\\CAPSTONE CLASS\\Photos\\download (2).jpg",
            "link": "https://www.youtube.com/watch?v=9TY14neTClk"
        },
        "geometry": {"type": "Point", "coordinates": [-87.7029174, 41.64283963]}
    }]
}